name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: zakilisee

          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Generate Radical Snake Theme
        run: |
          sed -i 's/#39d353/#fe428e/g' dist/github-contribution-grid-snake.svg || true
          sed -i 's/#2ea043/#c13cff/g' dist/github-contribution-grid-snake.svg || true

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
